### ISSUE TITLE
GUI layout corrupt

### ISSUE THREAD

**Issue by onewaypub** [owncloud/notes-iOS-App#31] opened 2015-10-12 09:04 UTC
Hi when opening notes and adding a new note on iOS9 (iPhone and IPad) the layout of the app is strange. The first line is covered. See attachment.
![photo-2015-10-12-10-55-00_1973](https://cloud.githubusercontent.com/assets/3080663/10424643/084a1e5c-70d1-11e5-9437-87d458f0fe24.PNG)

**Comment by phedlund** [comment] 2015-10-12 15:18
Duplicate of #30. A fix has been submitted to Apple for review.

**Closed by phedlund** 2015-10-12 15:18 UTC
Labels: duplicate
