### ISSUE TITLE
App crashes when creating a new note and opening it

### ISSUE THREAD

**Issue by roymckenzie** [owncloud/notes-iOS-App#47] opened 2018-03-25 06:32 UTC
When creating a new note in the app, the app immediately opens the new note and promptly black-screens and then crashes.

Also, getting a lot of `Request failed: method not allowed (405)` errors in the slide-down banner.

**Comment by phedlund** [comment] 2018-03-28 00:10
Sounds like a permission error on the server. Are Notes working properly using the web interface?

**Comment by roymckenzie** [comment] 2018-03-28 00:18
Thanks for getting back to me @phedlund. They are working in the web interface. Any recommendations on where I should look regarding permissions on my end?

**Comment by phedlund** [comment] 2018-03-28 00:58
Look in the web server logs and the ownCloud/NextCloud logs.

**Comment by Arnauec** [comment] 2018-11-01 11:10
I'm having this issue too, any solution found?

**Comment by olsins** [comment] 2019-02-13 21:17
I got the same issue - did anyone find a solution?
this is the apache log
89.247.XX.XXX - Username [13/Feb/2019:22:11:50 +0100] "GET /nextcloud/apps/notes/api/v0.2/notes/66904?exclude=title%2Ccontent HTTP/1.1" 200 2173 "-" "iOCNotes/2.1.5 (iPhone; iOS 12.1.2; Scale/2.00)"

**Comment by olsins** [comment] 2019-02-13 21:44
I found the solution myself  - the QOwnNotesAPI has to be activated in order to make the app working

**Comment by phedlund** [comment] 2019-11-28 00:02
Closing as not a bug.

**Closed by phedlund** 2019-11-28 00:02 UTC

**Comment by mreiger** [comment] 2019-12-06 13:33
Hi - I had similar issues lately.
Here is what I noticed:
* When I enter the server URL as https://nextcloud.example.com/ :
Notes do get loaded but creating new notes or modifying notes fails with the 405 error mentioned.
In the apache log files I then have:
  * ... GET apps/notes/api/... with a return code of 200 - that's the successful loading of notes from the server
  * ... PUT apps/notes/api/... with a return code of 405 - these are the failed attempts at creating or modifying notes.
* If on the other hand I enter the server URL as https://nextcloud.example.com/index.php :
Everything works as it should; I see in the apache logs:
  * ... GET index.php/apps/notes/api/... with a return code of 200 as well as
  * ... PUT index.php/apps/notes/api/... with a return code of 200.

According to the API documentation https://github.com/nextcloud/notes/wiki/API-0.2 the latter is the right way. Which is confusing to me since the GET is successful and only the PUT fails.

From an end user point of view having to add the /ined.php to the base server URL is confusing since the "Nextcloud URL" is just https://nextcloud.example.com in most cases.
May I suggest checking the server URL for the appended /index.php and adding it to the API calls if the user did omit it?

**Comment by phedlund** [comment] 2019-12-09 00:38
The app does attempt to add /index.php if operations without it fail, but there might be room for some improvement. However, if Nextcloud is configured as documented (in particular https://docs.nextcloud.com/server/17/admin_manual/installation/source_installation.html#pretty-urls) there should not be any issues.
